main: de.iplexy.permsk.PermSk
name: PermSk
version: 2.0
api-version: 1.20
authors:
  - ShaneBee
  - iPlexy
website: https://iplexy.de
depend:
  - Skript
softdepend: [Vault, PermissionsEx, LuckPerms, UltraPermissions, GroupManager]
commands:
  PermSk:
      description: "Informations about PermSk"