main: de.iplexy.permsk.SkPerm
name: PermSk
version: 1.1
api-version: 1.19
authors:
  - ShaneBee
  - iPlexy
website: https://iplexy.de
depend:
  - Skript
softdepend: [Vault, PermissionsEx, LuckPerms, UltraPermissions, GroupManager]